version: 0.0
os: windows
files:
  - source: git@github.com:kartikfumakiya/CodeDeployGitHubDemo.git
    destination: C:\inetpub\wwwroot
hooks:
  BeforeInstall:
  - location: \before-install.ps1
    timeout: 900
  AfterInstall:
  - location: \after-install.ps1
    timeout: 900
