version: 0.0
os: windows
files:
  - source: \
    destination: C:\inetpub\wwwroot

hooks:
  BeforeInstall:
    - location: \stop_iis.ps1
      timeout: 300
      runas: Administrator

  AfterInstall:
    - location: \start_iis.ps1
      timeout: 300
      runas: Administrator
