name: Copy to IIS Server

on:
  push:
    branches:
      - main

jobs:
  copy_to_iis:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy files to IIS server
      run: |
        Get-ChildItem -Path "C:\actions-runner\_work\CodeDeployGitHubDemo\CodeDeployGitHubDemo" | ForEach-Object { Copy-Item $_.FullName -Destination "C:\inetpub\wwwroot" -Recurse -Force }
