name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy files to EC2
      run: |
        pscp -r -i ${{ secrets.kartikfumakiya }} ${{ github..github/workflows/main.yml}}\* ${{ secrets.Administrator }}@${{ secrets.10.0.1.176 }}:${{ secrets.C:\inetpub\wwwroot }}

    - name: Restart IIS
      run: |
        plink -i ${{ secrets.C:\kartikfumakiya.ppk }} ${{ secrets.Administrator }}@${{ secrets.10.0.1.176 }} 'iisreset'
